# Generated by Django 4.1.4 on 2023-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0046_member_usac_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=300, null=True),
        ),
    ]
