# Generated by Django 4.1.4 on 2023-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0048_auto_20230130_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('regional', 'Regional'), ('team', 'Team'), ('advocacy_volunteer', 'Advocacy, Volunteer'), ('promoter', 'Promoter')], max_length=32),
        ),
    ]
