# Generated by Django 4.1.4 on 2023-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0049_alter_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rss',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='rss_url',
            field=models.TextField(default='', null=True),
        ),
    ]
