# Generated by Django 4.1.4 on 2023-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0050_event_is_usac_permitted_event_permit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='permit_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
