# Generated by Django 4.1.4 on 2023-02-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0050_organization_rss_organization_rss_url'),
        ('cycling_org', '0051_alter_event_permit_no'),
    ]

    operations = [
    ]
