# Generated by Django 4.1.6 on 2023-02-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0051_alter_event_permit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='rss_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='waiver_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
