# Generated by Django 4.1.6 on 2023-02-18 14:38

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Event = apps.get_model("cycling_org", "Event")
    Event.objects.using(db_alias).filter(organization__isnull=True).update(publish_type='public')
    Event.objects.using(db_alias).filter(organization__isnull=False).update(publish_type='org_public')


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('cycling_org', '0052_event_featured_event_organization_rss_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publish_type',
            field=models.CharField(
                choices=[('public', 'Public'), ('org_public', 'Org Public'), ('org_private', 'Org Private')],
                max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='shared_org_perms',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
