# Generated by Django 4.1.4 on 2023-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0053_remove_organization_rss_alter_organization_rss_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_event',
            field=models.BooleanField(default=False),
        ),
    ]
