# Generated by Django 4.1.4 on 2023-02-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0054_event_featured_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='waiver_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
