# Generated by Django 4.1.7 on 2023-03-12 17:00

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Organization = apps.get_model("cycling_org", "Organization")
    Organization.objects.using(db_alias).all().filter(type='team').update(type='club')


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_org', '0055_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('regional', 'Regional'), ('club', 'Club'), ('advocacy_volunteer', 'Advocacy, Volunteer'), ('promoter', 'Promoter')], max_length=32),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
