# Generated by Django 4.1.7 on 2023-04-08 14:05

from django.db import migrations, models
import rest_framework.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ("cycling_org", "0056_alter_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="prefs",
            field=models.JSONField(
                blank=True, encoder=rest_framework.utils.encoders.JSONEncoder, null=True
            ),
        ),
    ]
