# Generated by Django 4.1.7 on 2023-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycling_org", "0057_alter_organization_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="membership_open",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="raceresult",
            name="category",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
