# Generated by Django 4.1.4 on 2023-01-30 07:25

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model("account", "User")
    for o in User.objects.using(db_alias).all():
        if o.email:
            o.email = o.email.lower()
            o.save(update_fields=['email'])


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_draft'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
