# Generated by Django 4.1.4 on 2023-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrh_account', '0005_auto_20230130_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_in_email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_of_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_agreement_waiver',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
